-- SCHEMAS AND EXTENSION

-- SCHEMA: sa
DROP SCHEMA IF EXISTS sa ;
CREATE SCHEMA IF NOT EXISTS sa
    AUTHORIZATION postgres;
	
-- SCHEMA: pa
DROP SCHEMA IF EXISTS pa;
CREATE SCHEMA IF NOT EXISTS pa
    AUTHORIZATION postgres;
	
-- PostGIS Extension
CREATE EXTENSION IF NOT EXISTS postgis;